# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# from protos import user_pb2 as protos_dot_user__pb2
import user_pb2 as protos_dot_user__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Define the user service with the login function
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
            '/user.UserService/Login',
            request_serializer=protos_dot_user__pb2.UserLoginRequest.SerializeToString,
            response_deserializer=protos_dot_user__pb2.ResponseLogin.FromString,
            _registered_method=True)
        self.SignUp = channel.unary_unary(
            '/user.UserService/SignUp',
            request_serializer=protos_dot_user__pb2.UserAuthRequest.SerializeToString,
            response_deserializer=protos_dot_user__pb2.SignUpResponse.FromString,
            _registered_method=True)
        self.GetUser = channel.unary_unary(
            '/user.UserService/GetUser',
            request_serializer=protos_dot_user__pb2.GetUserRequest.SerializeToString,
            response_deserializer=protos_dot_user__pb2.UserResponse.FromString,
            _registered_method=True)


class UserServiceServicer(object):
    """Define the user service with the login function
    """

    def Login(self, request, context):
        """Login method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignUp(self, request, context):
        """Sign-up method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Get-User method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Login': grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=protos_dot_user__pb2.UserLoginRequest.FromString,
            response_serializer=protos_dot_user__pb2.ResponseLogin.SerializeToString,
        ),
        'SignUp': grpc.unary_unary_rpc_method_handler(
            servicer.SignUp,
            request_deserializer=protos_dot_user__pb2.UserAuthRequest.FromString,
            response_serializer=protos_dot_user__pb2.SignUpResponse.SerializeToString,
        ),
        'GetUser': grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=protos_dot_user__pb2.GetUserRequest.FromString,
            response_serializer=protos_dot_user__pb2.UserResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.UserService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Define the user service with the login function
    """

    @staticmethod
    def Login(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserService/Login',
            protos_dot_user__pb2.UserLoginRequest.SerializeToString,
            protos_dot_user__pb2.ResponseLogin.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignUp(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserService/SignUp',
            protos_dot_user__pb2.UserAuthRequest.SerializeToString,
            protos_dot_user__pb2.SignUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserService/GetUser',
            protos_dot_user__pb2.GetUserRequest.SerializeToString,
            protos_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
